/**
 *
 *  PurchaseOrdersController.cc
 *  This file is generated by drogon_ctl
 *
 */

#include "PurchaseOrdersController.h"
#include <string>

void PurchaseOrdersController::getOne(const HttpRequestPtr& req,
                                      std::function<void(const HttpResponsePtr&)>&& callback,
                                      std::string&& id) {}

void PurchaseOrdersController::get(const HttpRequestPtr& req,
                                   std::function<void(const HttpResponsePtr&)>&& callback) {}
void PurchaseOrdersController::create(const HttpRequestPtr& req,
                                      std::function<void(const HttpResponsePtr&)>&& callback) {}
void PurchaseOrdersController::updateOne(const HttpRequestPtr& req,
                                         std::function<void(const HttpResponsePtr&)>&& callback,
                                         std::string&& id) {}

/*
void PurchaseOrdersController::update(const HttpRequestPtr &req,
                                      std::function<void(const HttpResponsePtr &)> &&callback)
{

}*/

void PurchaseOrdersController::deleteOne(const HttpRequestPtr& req,
                                         std::function<void(const HttpResponsePtr&)>&& callback,
                                         std::string&& id) {}
