/**
 *
 *  SuppliersController.cc
 *  This file is generated by drogon_ctl
 *
 */

#include "SuppliersController.h"
#include <string>


void SuppliersController::getOne(const HttpRequestPtr &req,
                                 std::function<void(const HttpResponsePtr &)> &&callback,
                                 std::string &&id)
{
}

void SuppliersController::get(const HttpRequestPtr &req,
                              std::function<void(const HttpResponsePtr &)> &&callback)
{
}
void SuppliersController::create(const HttpRequestPtr &req,
                                 std::function<void(const HttpResponsePtr &)> &&callback)
{
}
void SuppliersController::updateOne(const HttpRequestPtr &req,
                                    std::function<void(const HttpResponsePtr &)> &&callback,
                                    std::string &&id)
{
}

/*
void SuppliersController::update(const HttpRequestPtr &req,
                                 std::function<void(const HttpResponsePtr &)> &&callback)
{

}*/

void SuppliersController::deleteOne(const HttpRequestPtr &req,
                                    std::function<void(const HttpResponsePtr &)> &&callback,
                                    std::string &&id)
{
}
