/**
 *
 *  SuppliersController.h
 *  This file is generated by drogon_ctl
 *
 */

#pragma once

#include <drogon/HttpController.h>
using namespace drogon;
/**
 * @brief this class is created by the drogon_ctl command (drogon_ctl create controller -r
 * SuppliersController). this class is a restful API controller.
 */
class SuppliersController : public drogon::HttpController<SuppliersController> {
  public:
    METHOD_LIST_BEGIN
    // use METHOD_ADD to add your custom processing function here;
    METHOD_ADD(SuppliersController::getOne, "/api/suppliers/{1}", Get, Options);
    METHOD_ADD(SuppliersController::get, "/api/suppliers", Get, Options);
    METHOD_ADD(SuppliersController::create, "/api/suppliers", Post, Options);
    METHOD_ADD(SuppliersController::updateOne, "/api/suppliers/{1}", Put, Options);
    // METHOD_ADD(SuppliersController::update,"",Put,Options);
    METHOD_ADD(SuppliersController::deleteOne, "/api/suppliers/{1}", Delete, Options);
    METHOD_LIST_END

    void getOne(const HttpRequestPtr& req, std::function<void(const HttpResponsePtr&)>&& callback,
                std::string&& id);
    void updateOne(const HttpRequestPtr& req,
                   std::function<void(const HttpResponsePtr&)>&& callback, std::string&& id);
    void deleteOne(const HttpRequestPtr& req,
                   std::function<void(const HttpResponsePtr&)>&& callback, std::string&& id);
    void get(const HttpRequestPtr& req, std::function<void(const HttpResponsePtr&)>&& callback);
    void create(const HttpRequestPtr& req, std::function<void(const HttpResponsePtr&)>&& callback);

    //    void update(const HttpRequestPtr &req,
    //                std::function<void(const HttpResponsePtr &)> &&callback);
};
