/**
 *
 *  WarehousesController.cc
 *  This file is generated by drogon_ctl
 *
 */

#include "WarehousesController.h"
#include <string>

void WarehousesController::getOne(const HttpRequestPtr& req,
                                  std::function<void(const HttpResponsePtr&)>&& callback,
                                  std::string&& id) {}

void WarehousesController::get(const HttpRequestPtr& req,
                               std::function<void(const HttpResponsePtr&)>&& callback) {}
void WarehousesController::create(const HttpRequestPtr& req,
                                  std::function<void(const HttpResponsePtr&)>&& callback) {}
void WarehousesController::updateOne(const HttpRequestPtr& req,
                                     std::function<void(const HttpResponsePtr&)>&& callback,
                                     std::string&& id) {}

/*
void WarehousesController::update(const HttpRequestPtr &req,
                                  std::function<void(const HttpResponsePtr &)> &&callback)
{

}*/

void WarehousesController::deleteOne(const HttpRequestPtr& req,
                                     std::function<void(const HttpResponsePtr&)>&& callback,
                                     std::string&& id) {}
