/**
 *
 *  PurchaseOrders.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "PurchaseOrders.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::sqlite3;

const std::string PurchaseOrders::Cols::_order_id = "order_id";
const std::string PurchaseOrders::Cols::_product_id = "product_id";
const std::string PurchaseOrders::Cols::_supplier_id = "supplier_id";
const std::string PurchaseOrders::Cols::_warehouse_id = "warehouse_id";
const std::string PurchaseOrders::Cols::_quantity_ordered = "quantity_ordered";
const std::string PurchaseOrders::Cols::_order_date = "order_date";
const std::string PurchaseOrders::Cols::_expected_arrival_date = "expected_arrival_date";
const std::string PurchaseOrders::Cols::_status = "status";
const std::string PurchaseOrders::primaryKeyName = "order_id";
const bool PurchaseOrders::hasPrimaryKey = true;
const std::string PurchaseOrders::tableName = "purchase_orders";

const std::vector<typename PurchaseOrders::MetaData> PurchaseOrders::metaData_={
{"order_id","int64_t","integer",8,1,1,0},
{"product_id","int64_t","integer",8,0,0,1},
{"supplier_id","int64_t","integer",8,0,0,1},
{"warehouse_id","int64_t","integer",8,0,0,1},
{"quantity_ordered","int64_t","integer",8,0,0,1},
{"order_date","std::string","text",0,0,0,1},
{"expected_arrival_date","std::string","text",0,0,0,1},
{"status","std::string","text",0,0,0,1}
};
const std::string &PurchaseOrders::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
PurchaseOrders::PurchaseOrders(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["order_id"].isNull())
        {
            orderId_=std::make_shared<int64_t>(r["order_id"].as<int64_t>());
        }
        if(!r["product_id"].isNull())
        {
            productId_=std::make_shared<int64_t>(r["product_id"].as<int64_t>());
        }
        if(!r["supplier_id"].isNull())
        {
            supplierId_=std::make_shared<int64_t>(r["supplier_id"].as<int64_t>());
        }
        if(!r["warehouse_id"].isNull())
        {
            warehouseId_=std::make_shared<int64_t>(r["warehouse_id"].as<int64_t>());
        }
        if(!r["quantity_ordered"].isNull())
        {
            quantityOrdered_=std::make_shared<int64_t>(r["quantity_ordered"].as<int64_t>());
        }
        if(!r["order_date"].isNull())
        {
            orderDate_=std::make_shared<std::string>(r["order_date"].as<std::string>());
        }
        if(!r["expected_arrival_date"].isNull())
        {
            expectedArrivalDate_=std::make_shared<std::string>(r["expected_arrival_date"].as<std::string>());
        }
        if(!r["status"].isNull())
        {
            status_=std::make_shared<std::string>(r["status"].as<std::string>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 8 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            orderId_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            productId_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            supplierId_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            warehouseId_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            quantityOrdered_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            orderDate_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 6;
        if(!r[index].isNull())
        {
            expectedArrivalDate_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 7;
        if(!r[index].isNull())
        {
            status_=std::make_shared<std::string>(r[index].as<std::string>());
        }
    }

}

PurchaseOrders::PurchaseOrders(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 8)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            orderId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            productId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            supplierId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            warehouseId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[3]].asInt64());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            quantityOrdered_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[4]].asInt64());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            orderDate_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            expectedArrivalDate_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            status_=std::make_shared<std::string>(pJson[pMasqueradingVector[7]].asString());
        }
    }
}

PurchaseOrders::PurchaseOrders(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("order_id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["order_id"].isNull())
        {
            orderId_=std::make_shared<int64_t>((int64_t)pJson["order_id"].asInt64());
        }
    }
    if(pJson.isMember("product_id"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["product_id"].isNull())
        {
            productId_=std::make_shared<int64_t>((int64_t)pJson["product_id"].asInt64());
        }
    }
    if(pJson.isMember("supplier_id"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["supplier_id"].isNull())
        {
            supplierId_=std::make_shared<int64_t>((int64_t)pJson["supplier_id"].asInt64());
        }
    }
    if(pJson.isMember("warehouse_id"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["warehouse_id"].isNull())
        {
            warehouseId_=std::make_shared<int64_t>((int64_t)pJson["warehouse_id"].asInt64());
        }
    }
    if(pJson.isMember("quantity_ordered"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["quantity_ordered"].isNull())
        {
            quantityOrdered_=std::make_shared<int64_t>((int64_t)pJson["quantity_ordered"].asInt64());
        }
    }
    if(pJson.isMember("order_date"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["order_date"].isNull())
        {
            orderDate_=std::make_shared<std::string>(pJson["order_date"].asString());
        }
    }
    if(pJson.isMember("expected_arrival_date"))
    {
        dirtyFlag_[6]=true;
        if(!pJson["expected_arrival_date"].isNull())
        {
            expectedArrivalDate_=std::make_shared<std::string>(pJson["expected_arrival_date"].asString());
        }
    }
    if(pJson.isMember("status"))
    {
        dirtyFlag_[7]=true;
        if(!pJson["status"].isNull())
        {
            status_=std::make_shared<std::string>(pJson["status"].asString());
        }
    }
}

void PurchaseOrders::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 8)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            orderId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            productId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            supplierId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            warehouseId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[3]].asInt64());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            quantityOrdered_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[4]].asInt64());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            orderDate_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            expectedArrivalDate_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            status_=std::make_shared<std::string>(pJson[pMasqueradingVector[7]].asString());
        }
    }
}

void PurchaseOrders::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("order_id"))
    {
        if(!pJson["order_id"].isNull())
        {
            orderId_=std::make_shared<int64_t>((int64_t)pJson["order_id"].asInt64());
        }
    }
    if(pJson.isMember("product_id"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["product_id"].isNull())
        {
            productId_=std::make_shared<int64_t>((int64_t)pJson["product_id"].asInt64());
        }
    }
    if(pJson.isMember("supplier_id"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["supplier_id"].isNull())
        {
            supplierId_=std::make_shared<int64_t>((int64_t)pJson["supplier_id"].asInt64());
        }
    }
    if(pJson.isMember("warehouse_id"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["warehouse_id"].isNull())
        {
            warehouseId_=std::make_shared<int64_t>((int64_t)pJson["warehouse_id"].asInt64());
        }
    }
    if(pJson.isMember("quantity_ordered"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["quantity_ordered"].isNull())
        {
            quantityOrdered_=std::make_shared<int64_t>((int64_t)pJson["quantity_ordered"].asInt64());
        }
    }
    if(pJson.isMember("order_date"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["order_date"].isNull())
        {
            orderDate_=std::make_shared<std::string>(pJson["order_date"].asString());
        }
    }
    if(pJson.isMember("expected_arrival_date"))
    {
        dirtyFlag_[6] = true;
        if(!pJson["expected_arrival_date"].isNull())
        {
            expectedArrivalDate_=std::make_shared<std::string>(pJson["expected_arrival_date"].asString());
        }
    }
    if(pJson.isMember("status"))
    {
        dirtyFlag_[7] = true;
        if(!pJson["status"].isNull())
        {
            status_=std::make_shared<std::string>(pJson["status"].asString());
        }
    }
}

const int64_t &PurchaseOrders::getValueOfOrderId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(orderId_)
        return *orderId_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &PurchaseOrders::getOrderId() const noexcept
{
    return orderId_;
}
void PurchaseOrders::setOrderId(const int64_t &pOrderId) noexcept
{
    orderId_ = std::make_shared<int64_t>(pOrderId);
    dirtyFlag_[0] = true;
}
void PurchaseOrders::setOrderIdToNull() noexcept
{
    orderId_.reset();
    dirtyFlag_[0] = true;
}
const typename PurchaseOrders::PrimaryKeyType & PurchaseOrders::getPrimaryKey() const
{
    assert(orderId_);
    return *orderId_;
}

const int64_t &PurchaseOrders::getValueOfProductId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(productId_)
        return *productId_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &PurchaseOrders::getProductId() const noexcept
{
    return productId_;
}
void PurchaseOrders::setProductId(const int64_t &pProductId) noexcept
{
    productId_ = std::make_shared<int64_t>(pProductId);
    dirtyFlag_[1] = true;
}

const int64_t &PurchaseOrders::getValueOfSupplierId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(supplierId_)
        return *supplierId_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &PurchaseOrders::getSupplierId() const noexcept
{
    return supplierId_;
}
void PurchaseOrders::setSupplierId(const int64_t &pSupplierId) noexcept
{
    supplierId_ = std::make_shared<int64_t>(pSupplierId);
    dirtyFlag_[2] = true;
}

const int64_t &PurchaseOrders::getValueOfWarehouseId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(warehouseId_)
        return *warehouseId_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &PurchaseOrders::getWarehouseId() const noexcept
{
    return warehouseId_;
}
void PurchaseOrders::setWarehouseId(const int64_t &pWarehouseId) noexcept
{
    warehouseId_ = std::make_shared<int64_t>(pWarehouseId);
    dirtyFlag_[3] = true;
}

const int64_t &PurchaseOrders::getValueOfQuantityOrdered() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(quantityOrdered_)
        return *quantityOrdered_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &PurchaseOrders::getQuantityOrdered() const noexcept
{
    return quantityOrdered_;
}
void PurchaseOrders::setQuantityOrdered(const int64_t &pQuantityOrdered) noexcept
{
    quantityOrdered_ = std::make_shared<int64_t>(pQuantityOrdered);
    dirtyFlag_[4] = true;
}

const std::string &PurchaseOrders::getValueOfOrderDate() const noexcept
{
    static const std::string defaultValue = std::string();
    if(orderDate_)
        return *orderDate_;
    return defaultValue;
}
const std::shared_ptr<std::string> &PurchaseOrders::getOrderDate() const noexcept
{
    return orderDate_;
}
void PurchaseOrders::setOrderDate(const std::string &pOrderDate) noexcept
{
    orderDate_ = std::make_shared<std::string>(pOrderDate);
    dirtyFlag_[5] = true;
}
void PurchaseOrders::setOrderDate(std::string &&pOrderDate) noexcept
{
    orderDate_ = std::make_shared<std::string>(std::move(pOrderDate));
    dirtyFlag_[5] = true;
}

const std::string &PurchaseOrders::getValueOfExpectedArrivalDate() const noexcept
{
    static const std::string defaultValue = std::string();
    if(expectedArrivalDate_)
        return *expectedArrivalDate_;
    return defaultValue;
}
const std::shared_ptr<std::string> &PurchaseOrders::getExpectedArrivalDate() const noexcept
{
    return expectedArrivalDate_;
}
void PurchaseOrders::setExpectedArrivalDate(const std::string &pExpectedArrivalDate) noexcept
{
    expectedArrivalDate_ = std::make_shared<std::string>(pExpectedArrivalDate);
    dirtyFlag_[6] = true;
}
void PurchaseOrders::setExpectedArrivalDate(std::string &&pExpectedArrivalDate) noexcept
{
    expectedArrivalDate_ = std::make_shared<std::string>(std::move(pExpectedArrivalDate));
    dirtyFlag_[6] = true;
}

const std::string &PurchaseOrders::getValueOfStatus() const noexcept
{
    static const std::string defaultValue = std::string();
    if(status_)
        return *status_;
    return defaultValue;
}
const std::shared_ptr<std::string> &PurchaseOrders::getStatus() const noexcept
{
    return status_;
}
void PurchaseOrders::setStatus(const std::string &pStatus) noexcept
{
    status_ = std::make_shared<std::string>(pStatus);
    dirtyFlag_[7] = true;
}
void PurchaseOrders::setStatus(std::string &&pStatus) noexcept
{
    status_ = std::make_shared<std::string>(std::move(pStatus));
    dirtyFlag_[7] = true;
}

void PurchaseOrders::updateId(const uint64_t id)
{
    orderId_ = std::make_shared<int64_t>(static_cast<int64_t>(id));
}

const std::vector<std::string> &PurchaseOrders::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "product_id",
        "supplier_id",
        "warehouse_id",
        "quantity_ordered",
        "order_date",
        "expected_arrival_date",
        "status"
    };
    return inCols;
}

void PurchaseOrders::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getProductId())
        {
            binder << getValueOfProductId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getSupplierId())
        {
            binder << getValueOfSupplierId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getWarehouseId())
        {
            binder << getValueOfWarehouseId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getQuantityOrdered())
        {
            binder << getValueOfQuantityOrdered();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getOrderDate())
        {
            binder << getValueOfOrderDate();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getExpectedArrivalDate())
        {
            binder << getValueOfExpectedArrivalDate();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getStatus())
        {
            binder << getValueOfStatus();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> PurchaseOrders::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    if(dirtyFlag_[6])
    {
        ret.push_back(getColumnName(6));
    }
    if(dirtyFlag_[7])
    {
        ret.push_back(getColumnName(7));
    }
    return ret;
}

void PurchaseOrders::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getProductId())
        {
            binder << getValueOfProductId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getSupplierId())
        {
            binder << getValueOfSupplierId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getWarehouseId())
        {
            binder << getValueOfWarehouseId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getQuantityOrdered())
        {
            binder << getValueOfQuantityOrdered();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getOrderDate())
        {
            binder << getValueOfOrderDate();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getExpectedArrivalDate())
        {
            binder << getValueOfExpectedArrivalDate();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getStatus())
        {
            binder << getValueOfStatus();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value PurchaseOrders::toJson() const
{
    Json::Value ret;
    if(getOrderId())
    {
        ret["order_id"]=(Json::Int64)getValueOfOrderId();
    }
    else
    {
        ret["order_id"]=Json::Value();
    }
    if(getProductId())
    {
        ret["product_id"]=(Json::Int64)getValueOfProductId();
    }
    else
    {
        ret["product_id"]=Json::Value();
    }
    if(getSupplierId())
    {
        ret["supplier_id"]=(Json::Int64)getValueOfSupplierId();
    }
    else
    {
        ret["supplier_id"]=Json::Value();
    }
    if(getWarehouseId())
    {
        ret["warehouse_id"]=(Json::Int64)getValueOfWarehouseId();
    }
    else
    {
        ret["warehouse_id"]=Json::Value();
    }
    if(getQuantityOrdered())
    {
        ret["quantity_ordered"]=(Json::Int64)getValueOfQuantityOrdered();
    }
    else
    {
        ret["quantity_ordered"]=Json::Value();
    }
    if(getOrderDate())
    {
        ret["order_date"]=getValueOfOrderDate();
    }
    else
    {
        ret["order_date"]=Json::Value();
    }
    if(getExpectedArrivalDate())
    {
        ret["expected_arrival_date"]=getValueOfExpectedArrivalDate();
    }
    else
    {
        ret["expected_arrival_date"]=Json::Value();
    }
    if(getStatus())
    {
        ret["status"]=getValueOfStatus();
    }
    else
    {
        ret["status"]=Json::Value();
    }
    return ret;
}

std::string PurchaseOrders::toString() const
{
    return toJson().toStyledString();
}

Json::Value PurchaseOrders::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 8)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getOrderId())
            {
                ret[pMasqueradingVector[0]]=(Json::Int64)getValueOfOrderId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getProductId())
            {
                ret[pMasqueradingVector[1]]=(Json::Int64)getValueOfProductId();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getSupplierId())
            {
                ret[pMasqueradingVector[2]]=(Json::Int64)getValueOfSupplierId();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getWarehouseId())
            {
                ret[pMasqueradingVector[3]]=(Json::Int64)getValueOfWarehouseId();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getQuantityOrdered())
            {
                ret[pMasqueradingVector[4]]=(Json::Int64)getValueOfQuantityOrdered();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getOrderDate())
            {
                ret[pMasqueradingVector[5]]=getValueOfOrderDate();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[6].empty())
        {
            if(getExpectedArrivalDate())
            {
                ret[pMasqueradingVector[6]]=getValueOfExpectedArrivalDate();
            }
            else
            {
                ret[pMasqueradingVector[6]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[7].empty())
        {
            if(getStatus())
            {
                ret[pMasqueradingVector[7]]=getValueOfStatus();
            }
            else
            {
                ret[pMasqueradingVector[7]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getOrderId())
    {
        ret["order_id"]=(Json::Int64)getValueOfOrderId();
    }
    else
    {
        ret["order_id"]=Json::Value();
    }
    if(getProductId())
    {
        ret["product_id"]=(Json::Int64)getValueOfProductId();
    }
    else
    {
        ret["product_id"]=Json::Value();
    }
    if(getSupplierId())
    {
        ret["supplier_id"]=(Json::Int64)getValueOfSupplierId();
    }
    else
    {
        ret["supplier_id"]=Json::Value();
    }
    if(getWarehouseId())
    {
        ret["warehouse_id"]=(Json::Int64)getValueOfWarehouseId();
    }
    else
    {
        ret["warehouse_id"]=Json::Value();
    }
    if(getQuantityOrdered())
    {
        ret["quantity_ordered"]=(Json::Int64)getValueOfQuantityOrdered();
    }
    else
    {
        ret["quantity_ordered"]=Json::Value();
    }
    if(getOrderDate())
    {
        ret["order_date"]=getValueOfOrderDate();
    }
    else
    {
        ret["order_date"]=Json::Value();
    }
    if(getExpectedArrivalDate())
    {
        ret["expected_arrival_date"]=getValueOfExpectedArrivalDate();
    }
    else
    {
        ret["expected_arrival_date"]=Json::Value();
    }
    if(getStatus())
    {
        ret["status"]=getValueOfStatus();
    }
    else
    {
        ret["status"]=Json::Value();
    }
    return ret;
}

bool PurchaseOrders::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("order_id"))
    {
        if(!validJsonOfField(0, "order_id", pJson["order_id"], err, true))
            return false;
    }
    if(pJson.isMember("product_id"))
    {
        if(!validJsonOfField(1, "product_id", pJson["product_id"], err, true))
            return false;
    }
    else
    {
        err="The product_id column cannot be null";
        return false;
    }
    if(pJson.isMember("supplier_id"))
    {
        if(!validJsonOfField(2, "supplier_id", pJson["supplier_id"], err, true))
            return false;
    }
    else
    {
        err="The supplier_id column cannot be null";
        return false;
    }
    if(pJson.isMember("warehouse_id"))
    {
        if(!validJsonOfField(3, "warehouse_id", pJson["warehouse_id"], err, true))
            return false;
    }
    else
    {
        err="The warehouse_id column cannot be null";
        return false;
    }
    if(pJson.isMember("quantity_ordered"))
    {
        if(!validJsonOfField(4, "quantity_ordered", pJson["quantity_ordered"], err, true))
            return false;
    }
    else
    {
        err="The quantity_ordered column cannot be null";
        return false;
    }
    if(pJson.isMember("order_date"))
    {
        if(!validJsonOfField(5, "order_date", pJson["order_date"], err, true))
            return false;
    }
    else
    {
        err="The order_date column cannot be null";
        return false;
    }
    if(pJson.isMember("expected_arrival_date"))
    {
        if(!validJsonOfField(6, "expected_arrival_date", pJson["expected_arrival_date"], err, true))
            return false;
    }
    else
    {
        err="The expected_arrival_date column cannot be null";
        return false;
    }
    if(pJson.isMember("status"))
    {
        if(!validJsonOfField(7, "status", pJson["status"], err, true))
            return false;
    }
    return true;
}
bool PurchaseOrders::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                        const std::vector<std::string> &pMasqueradingVector,
                                                        std::string &err)
{
    if(pMasqueradingVector.size() != 8)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[3] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[4] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[5] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[6].empty())
      {
          if(pJson.isMember(pMasqueradingVector[6]))
          {
              if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[6] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[7].empty())
      {
          if(pJson.isMember(pMasqueradingVector[7]))
          {
              if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool PurchaseOrders::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("order_id"))
    {
        if(!validJsonOfField(0, "order_id", pJson["order_id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("product_id"))
    {
        if(!validJsonOfField(1, "product_id", pJson["product_id"], err, false))
            return false;
    }
    if(pJson.isMember("supplier_id"))
    {
        if(!validJsonOfField(2, "supplier_id", pJson["supplier_id"], err, false))
            return false;
    }
    if(pJson.isMember("warehouse_id"))
    {
        if(!validJsonOfField(3, "warehouse_id", pJson["warehouse_id"], err, false))
            return false;
    }
    if(pJson.isMember("quantity_ordered"))
    {
        if(!validJsonOfField(4, "quantity_ordered", pJson["quantity_ordered"], err, false))
            return false;
    }
    if(pJson.isMember("order_date"))
    {
        if(!validJsonOfField(5, "order_date", pJson["order_date"], err, false))
            return false;
    }
    if(pJson.isMember("expected_arrival_date"))
    {
        if(!validJsonOfField(6, "expected_arrival_date", pJson["expected_arrival_date"], err, false))
            return false;
    }
    if(pJson.isMember("status"))
    {
        if(!validJsonOfField(7, "status", pJson["status"], err, false))
            return false;
    }
    return true;
}
bool PurchaseOrders::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                      const std::vector<std::string> &pMasqueradingVector,
                                                      std::string &err)
{
    if(pMasqueradingVector.size() != 8)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
      if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
      {
          if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false))
              return false;
      }
      if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
      {
          if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool PurchaseOrders::validJsonOfField(size_t index,
                                      const std::string &fieldName,
                                      const Json::Value &pJson,
                                      std::string &err,
                                      bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 5:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 6:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 7:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
