/**
 *
 *  Suppliers.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "Suppliers.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::sqlite3;

const std::string Suppliers::Cols::_supplier_id = "supplier_id";
const std::string Suppliers::Cols::_name = "name";
const std::string Suppliers::Cols::_contact_info = "contact_info";
const std::string Suppliers::primaryKeyName = "supplier_id";
const bool Suppliers::hasPrimaryKey = true;
const std::string Suppliers::tableName = "suppliers";

const std::vector<typename Suppliers::MetaData> Suppliers::metaData_ = {
    {"supplier_id", "int64_t", "integer", 8, 1, 1, 0},
    {"name", "std::string", "text", 0, 0, 0, 1},
    {"contact_info", "std::string", "text", 0, 0, 0, 1}};
const std::string& Suppliers::getColumnName(size_t index) noexcept(false) {
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Suppliers::Suppliers(const Row& r, const ssize_t indexOffset) noexcept {
    if (indexOffset < 0) {
        if (!r["supplier_id"].isNull()) {
            supplierId_ = std::make_shared<int64_t>(r["supplier_id"].as<int64_t>());
        }
        if (!r["name"].isNull()) {
            name_ = std::make_shared<std::string>(r["name"].as<std::string>());
        }
        if (!r["contact_info"].isNull()) {
            contactInfo_ = std::make_shared<std::string>(r["contact_info"].as<std::string>());
        }
    } else {
        size_t offset = (size_t)indexOffset;
        if (offset + 3 > r.size()) {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if (!r[index].isNull()) {
            supplierId_ = std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 1;
        if (!r[index].isNull()) {
            name_ = std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if (!r[index].isNull()) {
            contactInfo_ = std::make_shared<std::string>(r[index].as<std::string>());
        }
    }
}

Suppliers::Suppliers(const Json::Value& pJson,
                     const std::vector<std::string>& pMasqueradingVector) noexcept(false) {
    if (pMasqueradingVector.size() != 3) {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if (!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0])) {
        dirtyFlag_[0] = true;
        if (!pJson[pMasqueradingVector[0]].isNull()) {
            supplierId_ =
                std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if (!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1])) {
        dirtyFlag_[1] = true;
        if (!pJson[pMasqueradingVector[1]].isNull()) {
            name_ = std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if (!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2])) {
        dirtyFlag_[2] = true;
        if (!pJson[pMasqueradingVector[2]].isNull()) {
            contactInfo_ = std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
}

Suppliers::Suppliers(const Json::Value& pJson) noexcept(false) {
    if (pJson.isMember("supplier_id")) {
        dirtyFlag_[0] = true;
        if (!pJson["supplier_id"].isNull()) {
            supplierId_ = std::make_shared<int64_t>((int64_t)pJson["supplier_id"].asInt64());
        }
    }
    if (pJson.isMember("name")) {
        dirtyFlag_[1] = true;
        if (!pJson["name"].isNull()) {
            name_ = std::make_shared<std::string>(pJson["name"].asString());
        }
    }
    if (pJson.isMember("contact_info")) {
        dirtyFlag_[2] = true;
        if (!pJson["contact_info"].isNull()) {
            contactInfo_ = std::make_shared<std::string>(pJson["contact_info"].asString());
        }
    }
}

void Suppliers::updateByMasqueradedJson(
    const Json::Value& pJson, const std::vector<std::string>& pMasqueradingVector) noexcept(false) {
    if (pMasqueradingVector.size() != 3) {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if (!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0])) {
        if (!pJson[pMasqueradingVector[0]].isNull()) {
            supplierId_ =
                std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if (!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1])) {
        dirtyFlag_[1] = true;
        if (!pJson[pMasqueradingVector[1]].isNull()) {
            name_ = std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if (!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2])) {
        dirtyFlag_[2] = true;
        if (!pJson[pMasqueradingVector[2]].isNull()) {
            contactInfo_ = std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
}

void Suppliers::updateByJson(const Json::Value& pJson) noexcept(false) {
    if (pJson.isMember("supplier_id")) {
        if (!pJson["supplier_id"].isNull()) {
            supplierId_ = std::make_shared<int64_t>((int64_t)pJson["supplier_id"].asInt64());
        }
    }
    if (pJson.isMember("name")) {
        dirtyFlag_[1] = true;
        if (!pJson["name"].isNull()) {
            name_ = std::make_shared<std::string>(pJson["name"].asString());
        }
    }
    if (pJson.isMember("contact_info")) {
        dirtyFlag_[2] = true;
        if (!pJson["contact_info"].isNull()) {
            contactInfo_ = std::make_shared<std::string>(pJson["contact_info"].asString());
        }
    }
}

const int64_t& Suppliers::getValueOfSupplierId() const noexcept {
    static const int64_t defaultValue = int64_t();
    if (supplierId_)
        return *supplierId_;
    return defaultValue;
}
const std::shared_ptr<int64_t>& Suppliers::getSupplierId() const noexcept {
    return supplierId_;
}
void Suppliers::setSupplierId(const int64_t& pSupplierId) noexcept {
    supplierId_ = std::make_shared<int64_t>(pSupplierId);
    dirtyFlag_[0] = true;
}
void Suppliers::setSupplierIdToNull() noexcept {
    supplierId_.reset();
    dirtyFlag_[0] = true;
}
const typename Suppliers::PrimaryKeyType& Suppliers::getPrimaryKey() const {
    assert(supplierId_);
    return *supplierId_;
}

const std::string& Suppliers::getValueOfName() const noexcept {
    static const std::string defaultValue = std::string();
    if (name_)
        return *name_;
    return defaultValue;
}
const std::shared_ptr<std::string>& Suppliers::getName() const noexcept {
    return name_;
}
void Suppliers::setName(const std::string& pName) noexcept {
    name_ = std::make_shared<std::string>(pName);
    dirtyFlag_[1] = true;
}
void Suppliers::setName(std::string&& pName) noexcept {
    name_ = std::make_shared<std::string>(std::move(pName));
    dirtyFlag_[1] = true;
}

const std::string& Suppliers::getValueOfContactInfo() const noexcept {
    static const std::string defaultValue = std::string();
    if (contactInfo_)
        return *contactInfo_;
    return defaultValue;
}
const std::shared_ptr<std::string>& Suppliers::getContactInfo() const noexcept {
    return contactInfo_;
}
void Suppliers::setContactInfo(const std::string& pContactInfo) noexcept {
    contactInfo_ = std::make_shared<std::string>(pContactInfo);
    dirtyFlag_[2] = true;
}
void Suppliers::setContactInfo(std::string&& pContactInfo) noexcept {
    contactInfo_ = std::make_shared<std::string>(std::move(pContactInfo));
    dirtyFlag_[2] = true;
}

void Suppliers::updateId(const uint64_t id) {
    supplierId_ = std::make_shared<int64_t>(static_cast<int64_t>(id));
}

const std::vector<std::string>& Suppliers::insertColumns() noexcept {
    static const std::vector<std::string> inCols = {"name", "contact_info"};
    return inCols;
}

void Suppliers::outputArgs(drogon::orm::internal::SqlBinder& binder) const {
    if (dirtyFlag_[1]) {
        if (getName()) {
            binder << getValueOfName();
        } else {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[2]) {
        if (getContactInfo()) {
            binder << getValueOfContactInfo();
        } else {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> Suppliers::updateColumns() const {
    std::vector<std::string> ret;
    if (dirtyFlag_[1]) {
        ret.push_back(getColumnName(1));
    }
    if (dirtyFlag_[2]) {
        ret.push_back(getColumnName(2));
    }
    return ret;
}

void Suppliers::updateArgs(drogon::orm::internal::SqlBinder& binder) const {
    if (dirtyFlag_[1]) {
        if (getName()) {
            binder << getValueOfName();
        } else {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[2]) {
        if (getContactInfo()) {
            binder << getValueOfContactInfo();
        } else {
            binder << nullptr;
        }
    }
}
Json::Value Suppliers::toJson() const {
    Json::Value ret;
    if (getSupplierId()) {
        ret["supplier_id"] = (Json::Int64)getValueOfSupplierId();
    } else {
        ret["supplier_id"] = Json::Value();
    }
    if (getName()) {
        ret["name"] = getValueOfName();
    } else {
        ret["name"] = Json::Value();
    }
    if (getContactInfo()) {
        ret["contact_info"] = getValueOfContactInfo();
    } else {
        ret["contact_info"] = Json::Value();
    }
    return ret;
}

std::string Suppliers::toString() const {
    return toJson().toStyledString();
}

Json::Value Suppliers::toMasqueradedJson(
    const std::vector<std::string>& pMasqueradingVector) const {
    Json::Value ret;
    if (pMasqueradingVector.size() == 3) {
        if (!pMasqueradingVector[0].empty()) {
            if (getSupplierId()) {
                ret[pMasqueradingVector[0]] = (Json::Int64)getValueOfSupplierId();
            } else {
                ret[pMasqueradingVector[0]] = Json::Value();
            }
        }
        if (!pMasqueradingVector[1].empty()) {
            if (getName()) {
                ret[pMasqueradingVector[1]] = getValueOfName();
            } else {
                ret[pMasqueradingVector[1]] = Json::Value();
            }
        }
        if (!pMasqueradingVector[2].empty()) {
            if (getContactInfo()) {
                ret[pMasqueradingVector[2]] = getValueOfContactInfo();
            } else {
                ret[pMasqueradingVector[2]] = Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if (getSupplierId()) {
        ret["supplier_id"] = (Json::Int64)getValueOfSupplierId();
    } else {
        ret["supplier_id"] = Json::Value();
    }
    if (getName()) {
        ret["name"] = getValueOfName();
    } else {
        ret["name"] = Json::Value();
    }
    if (getContactInfo()) {
        ret["contact_info"] = getValueOfContactInfo();
    } else {
        ret["contact_info"] = Json::Value();
    }
    return ret;
}

bool Suppliers::validateJsonForCreation(const Json::Value& pJson, std::string& err) {
    if (pJson.isMember("supplier_id")) {
        if (!validJsonOfField(0, "supplier_id", pJson["supplier_id"], err, true))
            return false;
    }
    if (pJson.isMember("name")) {
        if (!validJsonOfField(1, "name", pJson["name"], err, true))
            return false;
    } else {
        err = "The name column cannot be null";
        return false;
    }
    if (pJson.isMember("contact_info")) {
        if (!validJsonOfField(2, "contact_info", pJson["contact_info"], err, true))
            return false;
    } else {
        err = "The contact_info column cannot be null";
        return false;
    }
    return true;
}
bool Suppliers::validateMasqueradedJsonForCreation(
    const Json::Value& pJson, const std::vector<std::string>& pMasqueradingVector,
    std::string& err) {
    if (pMasqueradingVector.size() != 3) {
        err = "Bad masquerading vector";
        return false;
    }
    try {
        if (!pMasqueradingVector[0].empty()) {
            if (pJson.isMember(pMasqueradingVector[0])) {
                if (!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err,
                                      true))
                    return false;
            }
        }
        if (!pMasqueradingVector[1].empty()) {
            if (pJson.isMember(pMasqueradingVector[1])) {
                if (!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err,
                                      true))
                    return false;
            } else {
                err = "The " + pMasqueradingVector[1] + " column cannot be null";
                return false;
            }
        }
        if (!pMasqueradingVector[2].empty()) {
            if (pJson.isMember(pMasqueradingVector[2])) {
                if (!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err,
                                      true))
                    return false;
            } else {
                err = "The " + pMasqueradingVector[2] + " column cannot be null";
                return false;
            }
        }
    } catch (const Json::LogicError& e) {
        err = e.what();
        return false;
    }
    return true;
}
bool Suppliers::validateJsonForUpdate(const Json::Value& pJson, std::string& err) {
    if (pJson.isMember("supplier_id")) {
        if (!validJsonOfField(0, "supplier_id", pJson["supplier_id"], err, false))
            return false;
    } else {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if (pJson.isMember("name")) {
        if (!validJsonOfField(1, "name", pJson["name"], err, false))
            return false;
    }
    if (pJson.isMember("contact_info")) {
        if (!validJsonOfField(2, "contact_info", pJson["contact_info"], err, false))
            return false;
    }
    return true;
}
bool Suppliers::validateMasqueradedJsonForUpdate(
    const Json::Value& pJson, const std::vector<std::string>& pMasqueradingVector,
    std::string& err) {
    if (pMasqueradingVector.size() != 3) {
        err = "Bad masquerading vector";
        return false;
    }
    try {
        if (!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0])) {
            if (!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err,
                                  false))
                return false;
        } else {
            err = "The value of primary key must be set in the json object for update";
            return false;
        }
        if (!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1])) {
            if (!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err,
                                  false))
                return false;
        }
        if (!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2])) {
            if (!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err,
                                  false))
                return false;
        }
    } catch (const Json::LogicError& e) {
        err = e.what();
        return false;
    }
    return true;
}
bool Suppliers::validJsonOfField(size_t index, const std::string& fieldName,
                                 const Json::Value& pJson, std::string& err, bool isForCreation) {
    switch (index) {
        case 0:
            if (isForCreation) {
                err = "The automatic primary key cannot be set";
                return false;
            }
            if (pJson.isNull()) {
                return true;
            }
            if (!pJson.isInt64()) {
                err = "Type error in the " + fieldName + " field";
                return false;
            }
            break;
        case 1:
            if (pJson.isNull()) {
                err = "The " + fieldName + " column cannot be null";
                return false;
            }
            if (!pJson.isString()) {
                err = "Type error in the " + fieldName + " field";
                return false;
            }
            break;
        case 2:
            if (pJson.isNull()) {
                err = "The " + fieldName + " column cannot be null";
                return false;
            }
            if (!pJson.isString()) {
                err = "Type error in the " + fieldName + " field";
                return false;
            }
            break;
        default:
            err = "Internal error in the server";
            return false;
    }
    return true;
}
